/**:
  ros__parameters:
    moveit_servo:
      use_gazebo: false
      status_topic: "~/status"
      command_in_type: "unitless"
      scale:
        linear: 0.4
        rotational: 0.4
        joint: 0.4
      publish_period: 0.034
      low_latency_mode: false
      command_out_topic: "/servo_controller/commands"
      command_out_type: "std_msgs/Float64MultiArray"
      publish_joint_positions: true
      publish_joint_velocities: false
      publish_joint_accelerations: false
      use_smoothing: true
      smoothing_filter_plugin_name: "online_signal_smoothing::ButterworthFilterPlugin"
      is_primary_planning_scene_monitor: false
      move_group_name: "arm"
      planning_frame: "base_link"
      ee_frame_name: "link_6"
      robot_link_command_frame: "base_link"
      cartesian_command_in_topic: "~/delta_twist_cmds"
      joint_command_in_topic: "~/delta_joint_cmds"
      joint_topic: "/joint_states"
      incoming_command_timeout: 0.2
      num_outgoing_halt_msgs_to_publish: 4
      lower_singularity_threshold: 70.0
      hard_stop_singularity_threshold: 100.0
      joint_limit_margin: 0.01
      leaving_singularity_threshold_multiplier: 2.0
      check_collisions: false
      collision_check_rate: 10.0
      self_collision_proximity_threshold: 0.005
      scene_collision_proximity_threshold: 0.02